### ISSUE TITLE
Compile error on storage.get<u64>(string) usage

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/near-runtime-ts#39]
The following code no longer compiles:
  const u64get = storage.get<u64>("u64key");

This used to compile on previous version of assemblyscript dependency.

**Comment by janedegtiareva** [comment]
Error: [11:10:11] AssertionError: assertion failed
    at n.assert (/Users/evgueniadegtiareva/near/r2/node_modules/assemblyscript/dist/asc.js:1:702162)
    at e.asNullable (/Users/evgueniadegtiareva/near/r2/node_modules/assemblyscript/dist/assemblyscript.js:1:130187)

**Comment by janedegtiareva** [comment]
fixed on staging
